--
-- PostgreSQL database schema dump for competezone
--

-- Extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';

-- Custom Types
CREATE TYPE public.agenda_item_type AS ENUM (
    'BRIEFING',
    'HEAT',
    'REST',
    'AWARDS',
    'REGISTRATION',
    'WARMUP',
    'CUSTOM'
);

COMMENT ON TYPE public.agenda_item_type IS 'Tipos de actividades de agenda: briefing, heat, rest, awards, registration, warmup, custom';

CREATE TYPE public.registration_status AS ENUM (
    'PENDING',
    'CONFIRMED',
    'CANCELED'
);

COMMENT ON TYPE public.registration_status IS 'Estado de una inscripción a evento: pending, confirmed o canceled';

CREATE TYPE public.user_role AS ENUM (
    'ATHLETE',
    'GYM',
    'ADMIN'
);

COMMENT ON TYPE public.user_role IS 'Rol del usuario en la plataforma: athlete, gym o admin';

-- Functions
CREATE FUNCTION public.check_event_registration_constraints() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
v_max        int;
  v_deadline   date;
  v_confirmed  int;
BEGIN
  IF (TG_OP = 'INSERT' AND NEW.status = 'CONFIRMED')
     OR (TG_OP = 'UPDATE' AND NEW.status = 'CONFIRMED' AND OLD.status <> 'CONFIRMED') THEN

SELECT max_participants, registration_deadline
INTO v_max, v_deadline
FROM events
WHERE id = NEW.event_id
    FOR UPDATE;

IF v_deadline IS NULL THEN
      RAISE EXCEPTION 'Evento % no existe', NEW.event_id USING errcode = '23514';
END IF;

    IF (now()::date > v_deadline) THEN
      RAISE EXCEPTION 'Inscripciones cerradas para el evento %', NEW.event_id USING errcode = '23514';
END IF;

SELECT count(*) INTO v_confirmed
FROM event_registrations
WHERE event_id = NEW.event_id
  AND status   = 'CONFIRMED';

IF v_confirmed >= v_max THEN
      RAISE EXCEPTION 'Cupos completos para el evento %', NEW.event_id USING errcode = '23514';
END IF;
END IF;

RETURN NEW;
END$$;

COMMENT ON FUNCTION public.check_event_registration_constraints() IS 'Valida cupo y fecha límite al confirmar inscripciones';

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = now();
RETURN NEW;
END$$;

COMMENT ON FUNCTION public.set_updated_at() IS 'Trigger function: actualiza el campo updated_at con now() en updates';

-- Tables
CREATE TABLE public.categories (
    id integer NOT NULL,
    name text NOT NULL
);

COMMENT ON TABLE public.categories IS 'Catálogo de categorías de participación';
COMMENT ON COLUMN public.categories.id IS 'Identificador secuencial';
COMMENT ON COLUMN public.categories.name IS 'Nombre único de la categoría (p.ej. RX, Escalado)';

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.event_agenda_items (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    title text NOT NULL,
    description text,
    start_time time without time zone NOT NULL,
    duration_minutes integer NOT NULL,
    order_index integer DEFAULT 0 NOT NULL,
    item_type public.agenda_item_type NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT event_agenda_items_duration_minutes_check CHECK ((duration_minutes > 0))
);

COMMENT ON TABLE public.event_agenda_items IS 'Elementos individuales de la agenda de eventos';
COMMENT ON COLUMN public.event_agenda_items.id IS 'Identificador UUID del elemento de agenda';
COMMENT ON COLUMN public.event_agenda_items.event_id IS 'Evento al que pertenece';
COMMENT ON COLUMN public.event_agenda_items.title IS 'Título de la actividad';
COMMENT ON COLUMN public.event_agenda_items.description IS 'Descripción opcional de la actividad';
COMMENT ON COLUMN public.event_agenda_items.start_time IS 'Hora de inicio de la actividad';
COMMENT ON COLUMN public.event_agenda_items.duration_minutes IS 'Duración en minutos';
COMMENT ON COLUMN public.event_agenda_items.order_index IS 'Orden de aparición en la agenda';
COMMENT ON COLUMN public.event_agenda_items.item_type IS 'Tipo de actividad';
COMMENT ON COLUMN public.event_agenda_items.created_at IS 'Fecha/hora de creación';
COMMENT ON COLUMN public.event_agenda_items.updated_at IS 'Fecha/hora de última modificación';

CREATE TABLE public.event_categories (
    event_id uuid NOT NULL,
    category_id integer NOT NULL
);

COMMENT ON TABLE public.event_categories IS 'Relación N:M entre eventos y categorías';
COMMENT ON COLUMN public.event_categories.event_id IS 'Evento';
COMMENT ON COLUMN public.event_categories.category_id IS 'Categoría';

CREATE TABLE public.event_leaderboard_cache (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    athlete_user_id uuid NOT NULL,
    category_name character varying(100),
    final_rank integer NOT NULL,
    result_value text,
    result_raw numeric(15,4),
    percentile numeric(5,2),
    cached_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.event_leaderboard_cache IS 'Cache de rankings precomputados para eventos';
COMMENT ON COLUMN public.event_leaderboard_cache.id IS 'Identificador UUID del cache';
COMMENT ON COLUMN public.event_leaderboard_cache.event_id IS 'Evento del ranking';
COMMENT ON COLUMN public.event_leaderboard_cache.athlete_user_id IS 'Atleta en el ranking';
COMMENT ON COLUMN public.event_leaderboard_cache.category_name IS 'Categoría de competencia';
COMMENT ON COLUMN public.event_leaderboard_cache.final_rank IS 'Posición final en el ranking';
COMMENT ON COLUMN public.event_leaderboard_cache.result_value IS 'Valor formateado para mostrar';
COMMENT ON COLUMN public.event_leaderboard_cache.result_raw IS 'Valor crudo para ordenamiento';
COMMENT ON COLUMN public.event_leaderboard_cache.percentile IS 'Percentil del participante';
COMMENT ON COLUMN public.event_leaderboard_cache.cached_at IS 'Fecha/hora de actualización del cache';

CREATE TABLE public.event_registrations (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    athlete_user_id uuid NOT NULL,
    status public.registration_status DEFAULT 'CONFIRMED'::public.registration_status NOT NULL,
    registered_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.event_registrations IS 'Inscripciones de usuarios (atletas) a eventos';
COMMENT ON COLUMN public.event_registrations.id IS 'Identificador UUID de la inscripción';
COMMENT ON COLUMN public.event_registrations.event_id IS 'Evento al que se inscribe';
COMMENT ON COLUMN public.event_registrations.athlete_user_id IS 'Usuario atleta inscrito';
COMMENT ON COLUMN public.event_registrations.status IS 'Estado de la inscripción';
COMMENT ON COLUMN public.event_registrations.registered_at IS 'Fecha/hora de registro';

CREATE TABLE public.event_results (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    athlete_user_id uuid NOT NULL,
    registration_id uuid,
    time_value interval,
    numeric_value numeric(15,4),
    rank_value integer,
    wins integer DEFAULT 0,
    losses integer DEFAULT 0,
    draws integer DEFAULT 0,
    bib_number character varying(10),
    team_name character varying(100),
    category_name character varying(100),
    notes text,
    is_official boolean DEFAULT true NOT NULL,
    recorded_by uuid,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    final_rank integer,
    percentile_rank numeric(5,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.event_results IS 'Resultados de rendimiento de participantes en eventos';
COMMENT ON COLUMN public.event_results.id IS 'Identificador UUID del resultado';
COMMENT ON COLUMN public.event_results.event_id IS 'Evento en el que se obtuvo el resultado';
COMMENT ON COLUMN public.event_results.athlete_user_id IS 'Usuario atleta que obtuvo el resultado';
COMMENT ON COLUMN public.event_results.registration_id IS 'Referencia a la inscripción del evento';
COMMENT ON COLUMN public.event_results.time_value IS 'Valor de tiempo para eventos basados en tiempo';
COMMENT ON COLUMN public.event_results.numeric_value IS 'Valor numérico para puntos, distancia, peso, etc.';
COMMENT ON COLUMN public.event_results.rank_value IS 'Valor de posición para resultados basados en ubicación';
COMMENT ON COLUMN public.event_results.wins IS 'Victorias (deportes de combate)';
COMMENT ON COLUMN public.event_results.losses IS 'Derrotas (deportes de combate)';
COMMENT ON COLUMN public.event_results.draws IS 'Empates (deportes de combate)';
COMMENT ON COLUMN public.event_results.bib_number IS 'Número de dorsal o identificación';
COMMENT ON COLUMN public.event_results.team_name IS 'Nombre del equipo (para competencias por equipos)';
COMMENT ON COLUMN public.event_results.category_name IS 'Categoría de competencia (RX, Scaled, etc.)';
COMMENT ON COLUMN public.event_results.notes IS 'Notas del juez, penalizaciones, etc.';
COMMENT ON COLUMN public.event_results.is_official IS 'Indica si el resultado es oficial';
COMMENT ON COLUMN public.event_results.recorded_by IS 'Usuario que registró el resultado';
COMMENT ON COLUMN public.event_results.recorded_at IS 'Fecha/hora de registro del resultado';
COMMENT ON COLUMN public.event_results.final_rank IS 'Posición final calculada en el evento';
COMMENT ON COLUMN public.event_results.percentile_rank IS 'Rango percentil (0-100)';
COMMENT ON COLUMN public.event_results.created_at IS 'Fecha/hora de creación';
COMMENT ON COLUMN public.event_results.updated_at IS 'Fecha/hora de última modificación';

CREATE TABLE public.events (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    organizer_user_id uuid NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    date date NOT NULL,
    "time" time without time zone NOT NULL,
    end_time time without time zone,
    location_text text NOT NULL,
    fee numeric(10,2) DEFAULT 0 NOT NULL,
    image_url text,
    registration_deadline date NOT NULL,
    max_participants integer NOT NULL,
    featured boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT events_check CHECK ((registration_deadline <= date)),
    CONSTRAINT events_max_participants_check CHECK ((max_participants > 0)),
    CONSTRAINT events_time_check CHECK (((end_time IS NULL) OR (end_time > "time")))
);

COMMENT ON TABLE public.events IS 'Eventos/competiciones publicados por usuarios con rol GYM';
COMMENT ON COLUMN public.events.id IS 'Identificador UUID del evento';
COMMENT ON COLUMN public.events.organizer_user_id IS 'Usuario organizador (rol GYM)';
COMMENT ON COLUMN public.events.title IS 'Título del evento';
COMMENT ON COLUMN public.events.description IS 'Descripción del evento';
COMMENT ON COLUMN public.events.date IS 'Fecha del evento (día)';
COMMENT ON COLUMN public.events."time" IS 'Hora de inicio';
COMMENT ON COLUMN public.events.end_time IS 'Hora de finalización (calculada automáticamente)';
COMMENT ON COLUMN public.events.location_text IS 'Ubicación libre mostrada en UI';
COMMENT ON COLUMN public.events.fee IS 'Cuota de inscripción';
COMMENT ON COLUMN public.events.image_url IS 'Imagen/banner del evento';
COMMENT ON COLUMN public.events.registration_deadline IS 'Fecha límite para inscribirse';
COMMENT ON COLUMN public.events.max_participants IS 'Cupo máximo de participantes';
COMMENT ON COLUMN public.events.featured IS 'Marcado como destacado';
COMMENT ON COLUMN public.events.created_at IS 'Fecha/hora de creación';
COMMENT ON COLUMN public.events.updated_at IS 'Fecha/hora de última modificación';

CREATE TABLE public.events_with_counters AS
 SELECT e.id,
    e.organizer_user_id,
    e.title,
    e.description,
    e.date,
    e."time",
    e.end_time,
    e.location_text,
    e.fee,
    e.image_url,
    e.registration_deadline,
    e.max_participants,
    e.featured,
    e.created_at,
    e.updated_at,
    COALESCE(( SELECT count(*) AS count
           FROM public.event_registrations er
          WHERE ((er.event_id = e.id) AND (er.status = 'CONFIRMED'::public.registration_status))), (0)::bigint) AS current_participants
   FROM public.events e;

COMMENT ON VIEW public.events_with_counters IS 'Eventos con campo calculado current_participants (inscripciones confirmadas)';

CREATE TABLE public.media (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    owner_type text NOT NULL,
    owner_id uuid NOT NULL,
    role text NOT NULL,
    key text NOT NULL,
    mime_type text NOT NULL,
    size_bytes bigint NOT NULL,
    width integer,
    height integer,
    is_public boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.media IS 'Tabla para gestión de archivos multimedia (imágenes)';
COMMENT ON COLUMN public.media.id IS 'Identificador UUID del archivo';
COMMENT ON COLUMN public.media.owner_type IS 'Tipo de entidad propietaria (ATHLETE, EVENT, WOD)';
COMMENT ON COLUMN public.media.owner_id IS 'ID de la entidad propietaria';
COMMENT ON COLUMN public.media.role IS 'Rol del archivo (ATHLETE_AVATAR, EVENT_BANNER, WOD_IMAGE)';
COMMENT ON COLUMN public.media.key IS 'Clave única del archivo (path relativo)';
COMMENT ON COLUMN public.media.mime_type IS 'Tipo MIME del archivo';
COMMENT ON COLUMN public.media.size_bytes IS 'Tamaño del archivo en bytes';
COMMENT ON COLUMN public.media.width IS 'Ancho de la imagen en píxeles (opcional)';
COMMENT ON COLUMN public.media.height IS 'Alto de la imagen en píxeles (opcional)';
COMMENT ON COLUMN public.media.is_public IS 'Indica si el archivo es público';
COMMENT ON COLUMN public.media.created_at IS 'Fecha y hora de creación';

CREATE TABLE public.refresh_tokens (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.refresh_tokens IS 'Refresh tokens para sesiones persistentes';
COMMENT ON COLUMN public.refresh_tokens.user_id IS 'Usuario dueño del token';
COMMENT ON COLUMN public.refresh_tokens.token IS 'Token (único) para refrescar acceso';
COMMENT ON COLUMN public.refresh_tokens.expires_at IS 'Expiración del refresh token';
COMMENT ON COLUMN public.refresh_tokens.revoked IS 'Marcado como revocado';
COMMENT ON COLUMN public.refresh_tokens.created_at IS 'Fecha de creación del token';

CREATE TABLE public.users (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    role public.user_role DEFAULT 'ATHLETE'::public.user_role NOT NULL,
    name text,
    bio text,
    location text,
    profile_image_url text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.users IS 'Usuarios del sistema (incluye atletas, dueños de gym y admins)';
COMMENT ON COLUMN public.users.id IS 'Identificador UUID';
COMMENT ON COLUMN public.users.email IS 'Correo del usuario (único)';
COMMENT ON COLUMN public.users.password_hash IS 'Hash de la contraseña';
COMMENT ON COLUMN public.users.role IS 'Rol del usuario: athlete|gym|admin';
COMMENT ON COLUMN public.users.name IS 'Nombre para mostrar';
COMMENT ON COLUMN public.users.bio IS 'Biografía corta';
COMMENT ON COLUMN public.users.location IS 'Ubicación libre (Ciudad, País)';
COMMENT ON COLUMN public.users.profile_image_url IS 'URL de imagen de perfil';
COMMENT ON COLUMN public.users.is_active IS 'Bandera de usuario activo';
COMMENT ON COLUMN public.users.created_at IS 'Fecha/hora de creación';
COMMENT ON COLUMN public.users.updated_at IS 'Fecha/hora de última modificación';

-- Constraints
ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_name_key UNIQUE (name);
    
ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.event_agenda_items
    ADD CONSTRAINT event_agenda_items_order_unique UNIQUE (event_id, order_index);
    
ALTER TABLE ONLY public.event_agenda_items
    ADD CONSTRAINT event_agenda_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.event_categories
    ADD CONSTRAINT event_categories_pkey PRIMARY KEY (event_id, category_id);

ALTER TABLE ONLY public.event_leaderboard_cache
    ADD CONSTRAINT event_leaderboard_cache_event_id_athlete_user_id_category_n_key UNIQUE (event_id, athlete_user_id, category_name);
    
ALTER TABLE ONLY public.event_leaderboard_cache
    ADD CONSTRAINT event_leaderboard_cache_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.event_registrations
    ADD CONSTRAINT event_registrations_event_id_athlete_user_id_key UNIQUE (event_id, athlete_user_id);
    
ALTER TABLE ONLY public.event_registrations
    ADD CONSTRAINT event_registrations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.event_results
    ADD CONSTRAINT event_results_event_id_athlete_user_id_category_name_key UNIQUE (event_id, athlete_user_id, category_name);
    
ALTER TABLE ONLY public.event_results
    ADD CONSTRAINT event_results_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_key_key UNIQUE (key);
    
ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
    
ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_key UNIQUE (token);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);
    
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- Indexes
CREATE INDEX idx_event_agenda_items_event ON public.event_agenda_items USING btree (event_id);
CREATE INDEX idx_event_agenda_items_order ON public.event_agenda_items USING btree (event_id, order_index);
CREATE INDEX idx_events_date ON public.events USING btree (date);
CREATE INDEX idx_events_location_text ON public.events USING gin (to_tsvector('simple'::regconfig, COALESCE(location_text, ''::text)));
CREATE INDEX idx_events_organizer ON public.events USING btree (organizer_user_id);
CREATE INDEX idx_events_search ON public.events USING gin (to_tsvector('spanish'::regconfig, ((COALESCE(title, ''::text) || ' '::text) || COALESCE(description, ''::text))));
CREATE INDEX idx_leaderboard_cache_athlete ON public.event_leaderboard_cache USING btree (athlete_user_id);
CREATE INDEX idx_leaderboard_cache_category ON public.event_leaderboard_cache USING btree (category_name);
CREATE INDEX idx_leaderboard_cache_event_rank ON public.event_leaderboard_cache USING btree (event_id, final_rank);
CREATE INDEX idx_media_created_at ON public.media USING btree (created_at);
CREATE INDEX idx_media_owner ON public.media USING btree (owner_type, owner_id);
CREATE INDEX idx_media_public ON public.media USING btree (is_public);
CREATE INDEX idx_media_role_owner ON public.media USING btree (role, owner_id);
CREATE INDEX idx_registrations_athlete ON public.event_registrations USING btree (athlete_user_id);
CREATE INDEX idx_registrations_event ON public.event_registrations USING btree (event_id);
CREATE INDEX idx_results_athlete ON public.event_results USING btree (athlete_user_id);
CREATE INDEX idx_results_category ON public.event_results USING btree (category_name);
CREATE INDEX idx_results_event ON public.event_results USING btree (event_id);
CREATE INDEX idx_results_rank ON public.event_results USING btree (final_rank);
CREATE INDEX idx_results_recorded_by ON public.event_results USING btree (recorded_by);

-- Triggers
CREATE TRIGGER trg_event_agenda_items_updated_at BEFORE UPDATE ON public.event_agenda_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
COMMENT ON TRIGGER trg_event_agenda_items_updated_at ON public.event_agenda_items IS 'Mantiene updated_at en event_agenda_items';

CREATE TRIGGER trg_event_regs_constraints BEFORE INSERT OR UPDATE ON public.event_registrations FOR EACH ROW EXECUTE FUNCTION public.check_event_registration_constraints();
COMMENT ON TRIGGER trg_event_regs_constraints ON public.event_registrations IS 'Enforce cupo y fecha límite al confirmar inscripción';

CREATE TRIGGER trg_event_results_updated_at BEFORE UPDATE ON public.event_results FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
COMMENT ON TRIGGER trg_event_results_updated_at ON public.event_results IS 'Mantiene updated_at en event_results';

CREATE TRIGGER trg_events_updated_at BEFORE UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
COMMENT ON TRIGGER trg_events_updated_at ON public.events IS 'Mantiene updated_at en events';

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
COMMENT ON TRIGGER trg_users_updated_at ON public.users IS 'Mantiene updated_at en users';

-- Foreign Key Constraints
ALTER TABLE ONLY public.event_agenda_items
    ADD CONSTRAINT event_agenda_items_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.event_categories
    ADD CONSTRAINT event_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.event_categories
    ADD CONSTRAINT event_categories_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.event_leaderboard_cache
    ADD CONSTRAINT event_leaderboard_cache_athlete_user_id_fkey FOREIGN KEY (athlete_user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.event_leaderboard_cache
    ADD CONSTRAINT event_leaderboard_cache_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.event_registrations
    ADD CONSTRAINT event_registrations_athlete_user_id_fkey FOREIGN KEY (athlete_user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.event_registrations
    ADD CONSTRAINT event_registrations_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.event_results
    ADD CONSTRAINT event_results_athlete_user_id_fkey FOREIGN KEY (athlete_user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.event_results
    ADD CONSTRAINT event_results_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.event_results
    ADD CONSTRAINT event_results_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.event_results
    ADD CONSTRAINT event_results_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES public.event_registrations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_organizer_user_id_fkey FOREIGN KEY (organizer_user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;